<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Moss</AssemblyName>
    <RootNamespace>Moss</RootNamespace>
    <ApplicationIcon>Assets\Moss.ico</ApplicationIcon>
    <DefaultItemExcludes>$(DefaultItemExcludes);work/**;outputs/**;offline-package/**</DefaultItemExcludes>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="Assets\Moss.ico" />
  </ItemGroup>
</Project>
